### PR TITLE
add dependency

### PR DESCRIPTION
**Pull request by FlorianHeigl**
needs git to complete ```make``` phase

### CODE REVIEW

**Comment by FlorianHeigl** [comment]
FYI: for ```docker-compose.yml``` I also needed to add the following to the mysql runtime parameters:

```
           --max-allowed-packet=67108864
```

it would be great if you could update the docker hub page for that.

**Comment by corro** [comment]
Thank you for your PR, contributions are always welcome! For which step is git required in the image?

I will update the example `docker-compose.yml` in Docker Hub, thank you for your suggestion.

**Comment by FlorianHeigl** [comment]
Hi @corro 
turns out I had enough scrollback buffer to find it - this is where it happened:

```
Step 15/22 : VOLUME ${ILIAS_DATA_PATH}
 ---> Running in da871034253f
Removing intermediate container da871034253f
 ---> b8e19346e6dd
Step 16/22 : ENV ILIAS_VERSION=6.0_beta2
 ---> Running in 487458f94e8a
Removing intermediate container 487458f94e8a
 ---> af79449c0f4c
Step 17/22 : ENV ILIAS_SHA1=10628afbfcca96ebf9846bc6c9026e02ec6fb5fc
 ---> Running in c114166e9837
Removing intermediate container c114166e9837
 ---> 21fbc801cf51
Step 18/22 : RUN curl -o ilias.tar.gz -SL https://github.com/ILIAS-eLearning/ILIAS/archive/v${ILIAS_VERSION}.tar.gz     && echo "$ILIAS_SHA1 *ilias.tar.gz" | sha1sum -c -     && tar -xzf ilias.tar.gz --strip-components=1     && rm ilias.tar.gz
 ---> Running in fc2eb59723f1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0   1031      0 --:--:-- --:--:-- --:--:--  1031
100  156M    0  156M    0     0  8703k      0 --:--:--  0:00:18 --:--:-- 6418k
ilias.tar.gz: OK
Removing intermediate container fc2eb59723f1
 ---> de30c1a8eeee
Step 19/22 : RUN echo "memory_limit=300M" > ${PHP_INI_DIR}/conf.d/composer.ini &&     composer install --no-dev -q -d libs/composer &&     rm ${PHP_INI_DIR}/conf.d/composer.ini
 ---> Running in 475bf3f0c3ad
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.

                                                                                                                             
  [RuntimeException]                                                                                                         
  Failed to clone https://github.com/sabre-io/http.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                             
  sh: 1: git: not found                                                                                                      
                                                                                                                             

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

The command '/bin/sh -c echo "memory_limit=300M" > ${PHP_INI_DIR}/conf.d/composer.ini &&     composer install --no-dev -q -d libs/composer &&     rm ${PHP_INI_DIR}/conf.d/composer.ini' returned a non-zero code: 1
make: *** [Makefile:30: 6-beta/php7.3-apache] Error 1
```

**Comment by corro** [comment]
Hmm, interesting. I cannot reproduce this issue. I'm not sure why it tries to clone the `source` url instead of using the `dist` url, which is accessible via http:
https://github.com/ILIAS-eLearning/ILIAS/blob/v6.0_beta2/libs/composer/composer.lock#L2086

Your build behaves as if the composer option `--prefer-source` was supplied, but I can't see where this would be the case.

I am a bit reluctant to add dependencies that are not absolutely needed. I hope you understand me there.

**Comment by FlorianHeigl** [comment]
@corro i didn't do anything beyond typing make. ;-)

**Comment by corro** [comment]
Now I ran into a similar error and was able to extract some more info:
```
  - Installing container-interop/container-interop (1.2.0): Downloading (0%)    Failed to download container-interop/container-interop from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing container-interop/container-interop (1.2.0): Cloning 79cbf1341c22ec75643d841642dd5d6acd83bdb8

                                                                                                                                                   
  [RuntimeException]                                                                                                                               
  Failed to clone https://github.com/container-interop/container-interop.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                                                   
  sh: 1: git: not found 
```

The relevant part is this one:
```
Failed to download container-interop/container-interop from dist: Could not authenticate against github.com
```

It fails to download the dependency from github.com and then falls back to cloning the source code with `git`. GitHub imposes a rate limit for requests (see https://developer.github.com/v3/#rate-limiting), I suspect this is the root cause for this issue. Maybe try it again in an hour or tomorrow?

**Comment by corro** [comment]
BTW: You can increase the verbosity of the `composer install` command by changing the `-q` flag to `-v`:
```diff
diff --git a/6-beta/Dockerfile b/6-beta/Dockerfile
index f7df573..3d6d41a 100644
--- a/6-beta/Dockerfile
+++ b/6-beta/Dockerfile
@@ -70,7 +70,7 @@ RUN curl -o ilias.tar.gz -SL https://github.com/ILIAS-eLearning/ILIAS/archive/v$
     && rm ilias.tar.gz
 
 RUN echo "memory_limit=300M" > ${PHP_INI_DIR}/conf.d/composer.ini && \
-    composer install --no-dev -q -d libs/composer && \
+    composer install --no-dev -v -d libs/composer && \
     rm ${PHP_INI_DIR}/conf.d/composer.ini
 
 COPY docker-ilias-entrypoint-setup-cli /usr/local/bin/docker-ilias-entrypoint
```

**Comment by FlorianHeigl** [comment]
For the sake of reproducibility it seems the most sane way would be to disable the git protocol fallback.
so the build would still abort, but the error would be the inaccessible download, not a tool that would not be needed if the download had worked.

**Comment by corro** [comment]
@FlorianHeigl, I agree and I would like to add such an option. Unfortunately it seems that composer does not support this use case. They specifically opted for not including a `--force-dist` option:
https://github.com/composer/composer/issues/4591

IMO, the only option we have is to increase the verbosity of `composer install`. This way we can at least see what is happening.

**Comment by corro** [comment]
I am closing this pull request due to inactivity. Thank you for your understanding.

**Pull request closed without merging**
